backend:
  name: github
  repo: MacStenk/stevennoack.de
  branch: main

local_backend: true

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string", required: true}
      - {label: "Beschreibung", name: "description", widget: "text", required: true, hint: "SEO-Beschreibung (max. 160 Zeichen)"}
      - {label: "TL;DR", name: "tldr", widget: "text", required: false, hint: "Ultra-Kurzzusammenfassung (1-2 Sätze für AI)"}
      - {label: "Autor", name: "author", widget: "string", default: "Steven Noack"}
      - {label: "Publikationsdatum", name: "pubDate", widget: "datetime", default: ""}
      - {label: "Zuletzt aktualisiert", name: "lastUpdated", widget: "datetime", required: false}
      - {label: "Sprache", name: "lang", widget: "select", options: ["de", "en", "de-DE", "en-US"], default: "de"}
      - label: "Kategorie" # ← Kategorien Anfang!
        name: "category"
        widget: "select"
        multiple: true  # ← Erlaubt Mehrfachauswahl!
        required: false
        default: "tech"
        hint: "Hauptkategorie des Posts"
        options:
          - { label: "🔧 Tech & Development", value: "tech" }
          - { label: "🤖 AI & Machine Learning", value: "ai" }
          - { label: "🔒 Privacy & Security", value: "privacy" }
          - { label: "🚀 DevOps & Docker", value: "devops" }
          - { label: "🎵 Techno & Culture", value: "culture" }
          - { label: "🧠 Consciousness", value: "consciousness" }
          - { label: "😊 Tutorial", value: "tutorial" }  # ← Kategorien Ende!
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "z.B.: ai, tutorial, python"}
      - {label: "Content-Typ", name: "contentType", widget: "select", options: ["Tutorial", "Guide", "News", "Review", "Opinion", "Case Study", "Documentation"], required: false}
      - {label: "Schwierigkeitsgrad", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced", "Expert"], required: false}
      - {label: "Zielgruppe", name: "audience", widget: "string", required: false, hint: "z.B.: Entwickler, Marketing Manager"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Featured Image Alt-Text", name: "featuredImageAlt", widget: "string", required: false}
      - label: "SEO"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Canonical URL", name: "canonical", widget: "string", required: false}
          - {label: "Keywords", name: "keywords", widget: "list", required: false}
          - {label: "OG Image", name: "ogImage", widget: "image", required: false}
          - {label: "OG Title", name: "ogTitle", widget: "string", required: false}
          - {label: "OG Description", name: "ogDescription", widget: "text", required: false}
          - {label: "Twitter Card", name: "twitterCard", widget: "select", options: ["summary", "summary_large_image"], default: "summary_large_image", required: false}
          - {label: "Robots", name: "robots", widget: "select", options: ["index,follow", "noindex,follow", "index,nofollow", "noindex,nofollow"], default: "index,follow", required: false}
          - {label: "Old URLs", name: "redirectFrom", widget: "list", required: false}
      - label: "Schema.org"
        name: "schema"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Type", name: "type", widget: "hidden", default: "BlogPosting"}
          - {label: "Published Date Override", name: "datePublished", widget: "datetime", required: false}
          - {label: "Modified Date", name: "dateModified", widget: "datetime", required: false}
      - label: "Autor-Details (E-E-A-T)"
        name: "authorDetails"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Website", name: "website", widget: "string", required: false}
          - {label: "Bio", name: "bio", widget: "text", required: false}
          - {label: "Social Profile", name: "social", widget: "string", required: false}
          - {label: "Credentials", name: "credentials", widget: "string", required: false}
      - {label: "Key Takeaways", name: "keyTakeaways", widget: "list", required: false}
      - {label: "Verwandte Posts", name: "relatedPosts", widget: "list", required: false}
      - {label: "Serie", name: "series", widget: "string", required: false}
      - {label: "Teil Nummer", name: "seriesPart", widget: "number", required: false}
      - label: "FAQ"
        name: "faq"
        widget: "list"
        collapsed: true
        required: false
        summary: "{{fields.question}}"
        fields:
          - {label: "Frage", name: "question", widget: "string"}
          - {label: "Antwort", name: "answer", widget: "text"}
      - label: "Update-Historie"
        name: "updateHistory"
        widget: "list"
        collapsed: true
        required: false
        summary: "{{fields.date}}"
        fields:
          - {label: "Datum", name: "date", widget: "datetime"}
          - {label: "Änderungen", name: "changes", widget: "text"}
      - {label: "Lesezeit", name: "readingTime", widget: "number", required: false}
      - {label: "Featured Post", name: "featured", widget: "boolean", default: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Priority", name: "priority", widget: "select", options: ["high", "normal", "low"], default: "normal", required: false}
      - {label: "Kommentare erlauben", name: "allowComments", widget: "boolean", default: true}
      - {label: "External Links: nofollow", name: "externalNofollow", widget: "boolean", default: false}
      - label: "Call-to-Action"
        name: "cta"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - {label: "Text", name: "text", widget: "string", required: false}
          - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown", hint: "Haupttext des Blog-Posts"}